export default [
  {
    "tier": 1,
    "description": "Tier 1: This Sensor Harness is fashioned from soft fabric with adjustable straps. It helps novice sensors steady their breathing during exercises."
  },
  {
    "tier": 2,
    "description": "Tier 2: This Sensor Harness employs reinforced stitching that holds sensory conduits in place. Light markings guide chakra flow across the chest."
  },
  {
    "tier": 3,
    "description": "Tier 3: This Sensor Harness includes flexible plates that guard vital organs without limiting perception. The design remains slim to avoid interference."
  },
  {
    "tier": 4,
    "description": "Tier 4: This Sensor Harness uses layered mesh to diffuse impacts while maintaining sensitivity. Breathable padding keeps the wearer comfortable during long vigils."
  },
  {
    "tier": 5,
    "description": "Tier 5: This Sensor Harness incorporates chakra-conductive threads that amplify detection range. Hidden vents release heat generated by continuous focus."
  },
  {
    "tier": 6,
    "description": "Tier 6: This Sensor Harness channels energy through engraved conduits to strengthen defenses. A gentle hum can be felt when the harness is active."
  },
  {
    "tier": 7,
    "description": "Tier 7: This Sensor Harness is aligned with a single elemental nature, allowing it to filter matching chakra signatures. An aura of that element briefly radiates when activated."
  },
  {
    "tier": 8,
    "description": "Tier 8: This Sensor Harness hides discreet pockets for sealing tags and communication tools. These additions do not obstruct sensing abilities."
  },
  {
    "tier": 9,
    "description": "Tier 9: This Sensor Harness bears etched formulas that can manifest protective barriers. The delicate symbols must be maintained for accuracy."
  },
  {
    "tier": 10,
    "description": "Tier 10: This Sensor Harness is optimized for quiet observation with noise-dampening materials. Matte surfaces prevent light from disrupting concentration."
  },
  {
    "tier": 11,
    "description": "Tier 11: This Sensor Harness is assigned to elite trackers and withstands sudden bursts of force. Chakra-absorbing padding around the ribs stabilizes focus."
  },
  {
    "tier": 12,
    "description": "Tier 12: This Sensor Harness is treated with oils from rare blossoms that heal minor tears. Wearers often notice a gentle fragrance during use."
  },
  {
    "tier": 13,
    "description": "Tier 13: This Sensor Harness is a relic from early sensory units. Its aged fabric carries the memory of distant signals once perceived."
  },
  {
    "tier": 14,
    "description": "Tier 14: This Sensor Harness serves as a clan heirloom adorned with subtle patterns that honor ancestral watchers. Each line reinforces a tradition of vigilance."
  },
  {
    "tier": 15,
    "description": "Tier 15: This Sensor Harness houses a living chakra filament that strengthens with experience. It gradually tunes itself to the wearer's perception style."
  },
  {
    "tier": 16,
    "description": "Tier 16: This Sensor Harness integrates fragments thought to originate from ancient divining gear. Its shielding effect peaks when facing overwhelming chakra signatures."
  },
  {
    "tier": 17,
    "description": "Tier 17: This Sensor Harness resonates with tailed-beast energy and grants bursts of clarity when chakra surges. Some claim distant echoes can be heard through it."
  },
  {
    "tier": 18,
    "description": "Tier 18: This Sensor Harness channels dual elements to construct layered sensing fields. Managing both streams demands exceptional control."
  },
  {
    "tier": 19,
    "description": "Tier 19: This Sensor Harness is infused with sap from the mythic God-Tree, letting heavy strikes drain a hint of vitality. Only a handful of artisans can craft it."
  },
  {
    "tier": 20,
    "description": "Tier 20: This Sensor Harness is an Ōtsutsuki-era artifact that transcends normal detection limits. Legends say it can perceive chakra from beyond the horizon."
  }
];
