export default [
  {
    "tier": 1,
    "description": "Tier 1: This Akatsuki Cloak is stitched from dark fabric with red lining. It offers minimal protection but bears the group's ominous style."
  },
  {
    "tier": 2,
    "description": "Tier 2: This Akatsuki Cloak uses reinforced seams that withstand harsh travel. The bold cloud patterns remain vivid through rain and wind."
  },
  {
    "tier": 3,
    "description": "Tier 3: This Akatsuki Cloak includes discreet plates sewn beneath the cloth. The design preserves a flowing silhouette for dramatic entrances."
  },
  {
    "tier": 4,
    "description": "Tier 4: This Akatsuki Cloak employs layered mesh that diffuses impact without bulking the garment. The interior stays comfortable during long marches."
  },
  {
    "tier": 5,
    "description": "Tier 5: This Akatsuki Cloak integrates high-grade alloy panels along the torso. Hidden vents release heat generated by prolonged use of jutsu."
  },
  {
    "tier": 6,
    "description": "Tier 6: This Akatsuki Cloak channels chakra through embroidered pathways to reinforce defense. A faint crimson glow traces the clouds when energized."
  },
  {
    "tier": 7,
    "description": "Tier 7: This Akatsuki Cloak is attuned to a single elemental nature and dampens related attacks. Upon activation, the cloth rustles with that element's presence."
  },
  {
    "tier": 8,
    "description": "Tier 8: This Akatsuki Cloak hides inner pockets for scrolls and tools. The storage compartments remain concealed beneath sweeping folds."
  },
  {
    "tier": 9,
    "description": "Tier 9: This Akatsuki Cloak bears etched sealing scripts that can unleash brief barriers. The markings require meticulous care to retain power."
  },
  {
    "tier": 10,
    "description": "Tier 10: This Akatsuki Cloak is crafted for silent movement with sound-dampening layers. Nonreflective fabric keeps the wearer hidden even under moonlight."
  },
  {
    "tier": 11,
    "description": "Tier 11: This Akatsuki Cloak is favored by high-ranking members and resists severe blows. Chakra-absorbent padding along the collar stabilizes energy flow."
  },
  {
    "tier": 12,
    "description": "Tier 12: This Akatsuki Cloak is treated with rare oils that repair minor tears. Wearers often sense a subtle chill when the coat seals itself."
  },
  {
    "tier": 13,
    "description": "Tier 13: This Akatsuki Cloak is a relic from the organization's early days. Its fabric whispers of secret plans and fallen comrades."
  },
  {
    "tier": 14,
    "description": "Tier 14: This Akatsuki Cloak serves as an heirloom bearing refined cloud insignia. Each stitch reflects the ambition of its former owners."
  },
  {
    "tier": 15,
    "description": "Tier 15: This Akatsuki Cloak houses a living chakra filament that deepens with experience. It subtly conforms to the wearer's unique presence."
  },
  {
    "tier": 16,
    "description": "Tier 16: This Akatsuki Cloak integrates fragments rumored to stem from celestial robes. Its protective aura peaks when confronting overwhelming opposition."
  },
  {
    "tier": 17,
    "description": "Tier 17: This Akatsuki Cloak resonates with tailed-beast energy and grants bursts of power when chakra surges. Some claim the clouds pulse in rhythm with the user's heart."
  },
  {
    "tier": 18,
    "description": "Tier 18: This Akatsuki Cloak channels dual elements to form complex defensive veils. Controlling both at once demands intense concentration."
  },
  {
    "tier": 19,
    "description": "Tier 19: This Akatsuki Cloak is infused with sap from the mythic God-Tree, enabling heavy blows to drain a trace of vitality. Few tailors dare attempt its creation."
  },
  {
    "tier": 20,
    "description": "Tier 20: This Akatsuki Cloak is an Ōtsutsuki-era garment that shrugs off conventional attacks. Legends say it can shroud its wearer in absolute darkness."
  }
];
