// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcptbolbmdiucrliluai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjcHRib2xibWRpdWNybGlsdWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTcxNjYsImV4cCI6MjA2OTU3MzE2Nn0.mmN2oG0vEIBLGrdMGTwXgOZm76WHGUX1tFLXw9Rw_CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});